name: GCP Docker Build
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      registry_path:
        required: true
        type: string
    secrets:
      GCP_SERVICE_ACCOUNT_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true
jobs:
  auth:
    uses: kcaparas1630/Github-Workflows/.github/workflows/gcp-auth-and-docker.yml@main
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  push:
    needs: auth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Push Docker Image
        run: |
          docker push ${{ inputs.registry_path }}/${{ inputs.image_name }}:latest
            
        
        
