name: GCP Docker Build
on:
  workflow_call:
    inputs:
        image_name:
          required: true
          type: string
        registry_path:
          required: true
          type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Authentication Setup
        uses: ./.github/workflows/gcp-auth-and-docker.yml@main
        with:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Push Docker Image
        run: |
          docker push ${{ inputs.registry_path }}/${{ inputs.image_name }}:latest
            
        
        
