name: GCP Docker Build
on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: false
        default: 'Dockerfile'
        type: string
      build_args:
        required: false
        default: ''
        type: string
      image_name:
        required: true
        type: string
      registry_path:
        required: true
        type: string
      tag_with_sha:
        required: false
        default: true
        type: boolean
    secrets:
      GCP_SERVICE_ACCOUNT_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
      
      - name: Build Docker Image
        run: |
          docker build -f ${{ inputs.dockerfile_path }} \
            ${{ inputs.build_args != '' && format('--build-arg {0}', inputs.build_args) || '' }} \
            -t ${{ inputs.registry_path }}/${{ inputs.image_name }}:latest \
            .
            
      - name: Push Docker image (latest)
        run: docker push ${{ inputs.registry_path }}/${{ inputs.image_name }}:latest
      
      - name: Tag and push with SHA
        if: ${{ inputs.tag_with_sha }}
        run: |
          docker tag ${{ inputs.registry_path }}/${{ inputs.image_name }}:latest ${{ inputs.registry_path }}/${{ inputs.image_name }}:${{ github.sha }}
          docker push ${{ inputs.registry_path }}/${{ inputs.image_name }}:${{ github.sha }}
