name: GCP Docker Build
on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: false
        default: 'Dockerfile'
        type: string
      build_args:
        required: false
        default: ''
        type: string
      image_name:
        required: true
        type: string
      registry_path:
        required: true
        type: string
      tag_with_sha:
        required: false
        default: true
        type: boolean
    secrets:
      GCP_SERVICE_ACCOUNT_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true
jobs:
  auth:
    uses: kcaparas1630/Github-Workflows/.github/workflows/gcp-auth-and-docker.yml@main
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  build:
    needs: auth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: |
          docker build -f ${{ inputs.dockerfile_path }} \
            --build-arg ${{ inputs.build_args }} \
            -t ${{ inputs.registry_path }}/${{ inputs.image_name }}:latest \
            .
            
      - name: Tag with SHA if enabled
        if: ${{ inputs.tag_with_sha }} |
        run: docker tag ${{ inputs.registry_path }}/${{ inputs.image_name }}:latest ${{ inputs.registry_path }}/${{ inputs.image_name }}:${{ github.sha }}
        
        
